### ISSUE TITLE
Text not rendered due to missing font

### ISSUE THREAD

**Issue by atsushieno** [szkkng/SimpleReverb#1]
I'm trying to use it on Linux, and it's working great except that it does not render any text.

![image](https://user-images.githubusercontent.com/53929/134640230-2dd3d02f-a12e-42af-a994-95717307cc8f.png)

That gives very professional feeling, but maybe too mucn for normal users :-)

I have a local fix, creating PR soon.

**Comment by szkkng** [comment]
Thank you for fixing!
