### ISSUE TITLE
The number position is just a little too high

### ISSUE THREAD

**Issue by suzukik1992** [szkkng/SimpleReverb#11]
The number position is just a little too high

**Comment by szkkng** [comment]
I lowered the position a little, is this fine?
<img width="543" alt="Screen Shot 2021-11-06 at 13 31 21" src="https://user-images.githubusercontent.com/61953352/140597932-b10f16a7-b93d-4781-acdb-25f32e0caaae.png">

**Comment by suzukik1992** [comment]
Now it's a little too low, so it's just a little above that.

**Comment by szkkng** [comment]
OK, I fixed it. 
<img width="543" alt="Screen Shot 2021-11-06 at 15 53 00" src="https://user-images.githubusercontent.com/61953352/140604934-45cd071c-7c26-4720-8ed0-32331ec6620b.png">
