### ISSUE TITLE
Eliminate the LED gradient on the dial for better visibility

### ISSUE THREAD

**Issue by suzukik1992** [szkkng/SimpleReverb#12]
Eliminate the LED gradient on the dial for better visibility

**Comment by szkkng** [comment]
Is this correct?
<img width="543" alt="Screen Shot 2021-11-06 at 13 15 16" src="https://user-images.githubusercontent.com/61953352/140597677-f9399f2d-1549-41b8-a7cd-7cb8ede1eacf.png">

**Comment by suzukik1992** [comment]
Yes, good work
